containers:
  - name: web # Leave it default if your application deploy in a single container style
    # If enable, `<release_name>-<container_name>-environment` secret must be manually created in the namespace.
    # This secret data will be populated into runtime as environment variables
    externalConfig: true
    resources: {}
      # limits:
      #  cpu: 100m
      #  memory: 128Mi
      # requests:
      #  cpu: 100m
      #  memory: 128Mi
service:
  enabled: true
  type: ClusterIP
  ports:
    - internal: 80 # Your application listen port
      external: 80 # Exposed port to the outside of container
ingress:
  enabled: true
  servicePort: 80 # Which service port should receive HTTP request