stages:
  - build
  - deploy
  - clean_all
build_image:
  stage: build
  script:
    - git clone git@git.edumall.io:backend/config-files.git /home/gitlab-runner/Git/config-files
    - pwd
    - DIR=$(pwd)
    - cp /home/gitlab-runner/Git/config-files/gaia/secrets.yml $DIR/config/
    - cp /home/gitlab-runner/Git/config-files/gaia/database.yml $DIR/config/
    - cp /home/gitlab-runner/Git/config-files/rsa-public-keys/authservice_jwt.pub $DIR/config/
    - docker build -t gaia:1.0.${CI_BUILD_REF} -f ./Dockerfile .
  only:
    - master@tcs/gaia
deploy:
  stage: deploy
  script:
    - bash /home/gitlab-runner/ecr-login.sh
    - docker tag gaia:1.0.${CI_BUILD_REF} 350339004156.dkr.ecr.ap-southeast-1.amazonaws.com/gaia:1.0.${CI_BUILD_ID}
    - docker push 350339004156.dkr.ecr.ap-southeast-1.amazonaws.com/gaia:1.0.${CI_BUILD_ID}
    - kubectl set image deployment/gaia gaia=350339004156.dkr.ecr.ap-southeast-1.amazonaws.com/gaia:1.0.${CI_BUILD_ID} -n marketing
  when: on_success
  environment:
    name: production
    url: https://apps.edumall.io
  only:
    - master@tcs/gaia
clean_all_build:
  stage: clean_all
  script:
    - rm -rf /home/gitlab-runner/Git/config-files
    - docker rmi -f gaia:1.0.${CI_BUILD_REF}
  when: always
  only:
    - master@tcs/gaia